### ISSUE TITLE
Inline code-blocks without max-width are causing odd page-displays on mobile.

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki#134]
![image](https://user-images.githubusercontent.com/18729296/126883444-585b0577-7500-4a4f-8ca1-22a44b123968.png)

**Comment by sermah** [comment]
Not only on mobile
![image](https://user-images.githubusercontent.com/40694307/126969995-44e2b761-3aa7-419d-8dc6-0b34a2ac380e.png)

**Comment by MedicalJewel105** [comment]
Fixed 😎
