### ISSUE TITLE
Broken Link and missing "EXP" mark

### ISSUE THREAD

**Issue by A1samo** [Bedrock-OSS/bedrock-wiki#135]
"Fake Blocks" missing a "EXP"(experimental) mark since it uses 1.16.100.
Also there is a broken link of "Solid Entities" in this link of "Fake Blocks"
https://wiki.bedrock.dev/blocks/fake-blocks.html

About the broken "Solid Entities" link at "Fake Blocks":
What I get is this:
https://wiki.bedrock.dev/tutorials/solid-entities.html
What I should get is this:
https://wiki.bedrock.dev/entities/solid-entities.html

**Comment by SirLich** [comment]
Done
