### ISSUE TITLE
TOC does not wrap if no spaces or breaks

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki#138]
![image](https://user-images.githubusercontent.com/18729296/126911107-0a216ba2-cc64-4c21-bdae-d8e9645f7887.png)

**Comment by stirante** [comment]
Fixed in https://github.com/Bedrock-OSS/bedrock-wiki/commit/5a7f40f0540646c1da87461cf70fc900bff65a0a
