### ISSUE TITLE
Youtube embeds don't resize to screen width

### ISSUE THREAD

**Issue by sermah** [Bedrock-OSS/bedrock-wiki#142]
I guess it's not a mobile-only issue, but a small-screen-width one.
![Screenshot_20210726-222347](https://user-images.githubusercontent.com/40694307/127046905-e8d5e100-0b86-484b-901f-05d1ef83d640.png)

**Comment by sermah** [comment]
#134 is very similar, but seems to have different roots.

**Comment by destruc7i0n** [comment]
Fixed in a801366293eb761bd9c7610d5ae6f280df6d935a
