### ISSUE TITLE
Custom Weapons outdated

### ISSUE THREAD

**Issue by yanasakana** [Bedrock-OSS/bedrock-wiki#151]
The Custom Weapons guide is outdated. Some of the main errors are as follows: 

- Manifest `"min_engine_version"` is not required to be set to `1.16.100`, though should preferably be set to `1.17.1` or higher.

- Automatic weapon durability is broken as of latest stable (and probably beta, too, haven't tested). A damage event is required.

- Falsely suggests that "adding `"minecraft:mining_speed": 1.5`.." will do anything. Currently broken/useless.

- Recipe should be format version `1.12.0`.

**Comment by MedicalJewel105** [comment]
I will do it
