### ISSUE TITLE
Vanilla usage

### ISSUE THREAD

**Issue by IlkinQafarov** [Bedrock-OSS/bedrock-wiki#159]
Hello! I couldn't find where is the Vanilla Usage section on new wiki. I know the place on old one, but couldn't find on new.

**Comment by IlkinQafarov** [comment]
Lol, I mean is there Vanilla Usage section?

**Comment by aexer0e** [comment]
There is no Vanilla Usage section anymore, but the pages are still present under the Entities section.

![image](https://user-images.githubusercontent.com/59780229/130290697-685222dc-dace-4f9f-a320-b6c92f88ef0f.png)

**Comment by IlkinQafarov** [comment]
Nice, ty:D
