### ISSUE TITLE
add a page about different pieces of software

### ISSUE THREAD

**Issue by minerj101** [Bedrock-OSS/bedrock-wiki#177]
There are many different pieces of software for Minecraft Bedrock. 

I think it would be nice to promote different pieces of software. 

Like how there is a plan to mention other server software, why not make a page on other software you can use and develop with. 

There can be a possibility of including alternative clients, 
I found a client written in C# here on GitHub.
[Link to the repo](https://github.com/kennyvv/Alex)

A few notable ones are 

- Mcc Toolchest and alternatives like universal Minecraft editor.
- The other software within bedrock oss
- Amulet World Editor

**Comment by MedicalJewel105** [comment]
https://wiki.bedrock.dev/meta/useful-links.html
It already exist but needs some things to be added. There are 2 NBT editors so MCC Toolchest is not needed.
Some of ones that you listed, are already added
