### ISSUE TITLE
Show sidebar pip in-page as well

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki#19]
Currently we need to write it into the title, or add it below as a widget. Can we just make sidebar pips display in the title too?

![image](https://user-images.githubusercontent.com/18729296/118788704-54a98b00-b894-11eb-8376-4ba37b03c15b.png)

**Comment by solvedDev** [comment]
We already have a system similar to this. We should be able to reuse it:

![image](https://user-images.githubusercontent.com/33347616/118994596-c3671100-b986-11eb-84d4-8a51570b17f8.png)
![image](https://user-images.githubusercontent.com/33347616/118994825-f14c5580-b986-11eb-859d-fecc31766297.png)

**Comment by SirLich** [comment]
Yes! I'm aware. I'm simply looking into using The Layout (or a custom Layout!) to do it automatically. 

I want to avoid as much double-work as possible when writing pages. If something is marked beta in the sidebar, I want it to be marked beta on the page as well.

**Comment by solvedDev** [comment]
Ah, I see. This should be an easy fix if we remove all `<h1>` headers from the markdown itself and instead have the page title inside of the frontmatter too

**Comment by SirLich** [comment]
Page title is already inside the front-matter, I believe. That's how we generate sidebar content. 

I'm still deciding whether I'm fully happy with that solution or not. Currently we sometimes use a different (shorter) title for the sidebar, and provide more information for the in-page h1. 

But I will look into it. Still working on cracking the custom layouts.
