### ISSUE TITLE
Code blocks often show white, instead of showing Syntax Highlighting

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki#383]

**Comment by DJStompZone** [comment]
I can't seem to reproduce this! Can you include any more info on when/where this happens?

**Comment by SirLich** [comment]
@DJStompZone hey! It seems to be related to HOW you access a page. So if I visit the main site, and use the sidebar to select the item tutorial, I get this:
![image](https://user-images.githubusercontent.com/18729296/169646538-cfe20338-7ee7-4cc2-ab59-8592409c9345.png)

If I reload, I get this:

![image](https://user-images.githubusercontent.com/18729296/169646545-8da5d924-73f1-4bd4-884f-05636ed49ac0.png)

Maybe just some CSS load order or something. I'm just not having time to work on the website these days.

**Comment by Fabrimat** [comment]
HTML before reloading:
```html
<pre><code><span class="token property">"description"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token property">"identifier"</span><span class="token operator">:</span> <span class="token string">"wiki:entity_commands"</span><span class="token punctuation">,</span>
    <span class="token property">"scripts"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token property">"animate"</span><span class="token operator">:</span> <span class="token punctuation">[</span>
            <span class="token string">"wiki:entity_commands"</span>
        <span class="token punctuation">]</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token property">"animations"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token property">"wiki:entity_commands"</span><span class="token operator">:</span> <span class="token string">"controller.animation.wiki_entity_commands"</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre>
```
After:
```html
<pre class="language-json" tabindex="0"><code class="language-json">"description": {
    "identifier": "wiki:entity_commands",
    "scripts": {
        "animate": [
            "wiki:entity_commands"
        ]
    },
    "animations": {
        "wiki:entity_commands": "controller.animation.wiki_entity_commands"
    }
}
</code></pre>
```

And it seems to persist also when using other browsers (Server side?)

**Comment by JaylyDev** [comment]
![image](https://user-images.githubusercontent.com/65847850/190920283-c91a8cb4-983c-4bc2-8eb1-832feb45b055.png)

After the page reload there seems to be a lot of missing js files in the webpage.

> Working webpage redirects from main page https://wiki.bedrock.dev
> Broken webpage by loading it for the first time or redirect from external website
