### ISSUE TITLE
Make more interesting styling for checkboxes

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki#40]
![image](https://user-images.githubusercontent.com/18729296/119036729-5cab1d00-b9b1-11eb-9943-ef4717f94c76.png)

@KaiFireborn I assigned you here, since this would mostly impact the guide, and I thought you might be interested. Feel free to remove yourself. 

I also put it at v1.1 milestone, so there isn't any rush.

**Comment by MedicalJewel105** [comment]
https://www.npmjs.com/package/@gerhobbelt/markdown-it-checkbox
