### ISSUE TITLE
Wiki animation categories !

### ISSUE THREAD

**Issue by Zaelee** [Bedrock-OSS/bedrock-wiki#458]
I would like to know if it is possible of course to rephrase certain passage, because I find myself with several files more than 2 whereas in the wiki it says that 2 me I have 4 ! Please

**Comment by Hatchibombotar** [comment]
Could you give a link to the page in question and re-phrase what you mean?

**Comment by Zaelee** [comment]
https://wiki.bedrock.dev/json-ui/aseprite-animations.html (screenshots are missing)

**Comment by MedicalJewel105** [comment]
They are not pictures, it is a folder view. What for you need that images?
