### ISSUE TITLE
Recommended extension does not exist

### ISSUE THREAD

**Issue by AdamRaichu** [Bedrock-OSS/bedrock-wiki#535]
**Issue:** Opening the repo in vscode web (github.dev) generates the following error.

```
The 1 extension(s) below, in workspace recommendations have issues: johnsoncodehk.volar (not found in marketplace)
```

**Affected pages:** [vscode web](https://github.dev/Bedrock-OSS/bedrock-wiki/tree/wiki)

Suggestions: Remove from recommendations list.

**Comment by SmokeyStack** [comment]
It seems it has been updated to `Vue.volar` instead according to the [gh repo](https://github.com/johnsoncodehk/volar) and [marketplace](https://marketplace.visualstudio.com/items?itemName=Vue.volar). If anyone else can confirm this we can update the `.vscode` folder accordingly.
