### ISSUE TITLE
Creating a short description for each page

### ISSUE THREAD

**Issue by TheItsNameless** [Bedrock-OSS/bedrock-wiki#545]
Issue:
Since we now use OpenGraph metadata to show better link embeds when linking to pages in the wiki, we need a description for every page. Currently the metadata falls back to a default description, which describes the wiki and not the pages in it.

If there is someone who has time and wants to read all of our articles, it would be great to add a description in the frontmatter of the pages.

To add a description for a page, simply expand the frontmatter by adding:

```
---
...
title: ...
description: Your page description! It should be about 2 sentences long.
---
```

Page:
All of them

Suggestions:
No suggestion, this just might take a while.

**Comment by MedicalJewel105** [comment]
Do we need to update the bot so it searches wiki based on meta data too?
