### ISSUE TITLE
json-ui: draggable does not accept bool

### ISSUE THREAD

**Issue by inxomnyaa** [Bedrock-OSS/bedrock-wiki#567]
Issue:
The client gives a content error if bool

Page: https://wiki.bedrock.dev/json-ui/json-ui-documentation.html#layout

Suggestions:
I am guessing the type is string
`ui_common.json`:
```json
          "draggable": "vertical"
```

**Comment by MedicalJewel105** [comment]
Not stated that type is bool, it is enumerate. Probably already updated.
![image](https://github.com/user-attachments/assets/d2fdabbc-9978-4ad0-881a-1bbaa52a92e7)
