### ISSUE TITLE
Only fetch contributor data during build

### ISSUE THREAD

**Issue by solvedDev** [Bedrock-OSS/bedrock-wiki#58]
Currently, a fetch request happens upon navigating to a page which is unnecessary because the contributors data cannot change independently from the page.

Move logic to config.js file instead

**Comment by aexer0e** [comment]
Implemented with  #https://github.com/Bedrock-OSS/bedrock-wiki/commit/4cfb4318018bbf7875c15c1bbb30b08a0f830ad7 :)
