### ISSUE TITLE
Content Issue: blocks drop can not be altered in bedrock edition

### ISSUE THREAD

**Issue by guplem** [Bedrock-OSS/bedrock-wiki#614]
Issue: In the [loot tables integration section](https://wiki.bedrock.dev/loot/loot-tables.html#integration) there is a reference to the possibility to modify the loot tables of blocks, but it is not possible to do so.

Page: https://wiki.bedrock.dev/loot/loot-tables.html#integration

Suggestions: I think that it should be specified that the block's drop cannot be altered. At least, I have not found any reference about the possibility of altering it. 
The [loot table page](https://wiki.bedrock.dev/loot/loot-tables.html#integration) should not hint that it is possible by showing an example of the folder structure containing a "blocks" folder:
![image](https://user-images.githubusercontent.com/11029629/229289774-fd76f874-b8a4-438b-a891-82cda531b2d0.png)

**Comment by SmokeyStack** [comment]
Custom blocks can also have loot tables so the `blocks` folder is where the json file is stored. A better solution would be to put somewhere in the wiki that the loot table of vanilla blocks cannot be modified

**Comment by guplem** [comment]
> Custom blocks can also have loot tables so the `blocks` folder is where the json file is stored. A better solution would be to put somewhere in the wiki that the loot table of vanilla blocks cannot be modified

I agree with that. I was trying to modify the drop of vanilla blocks and I couldn't find a way.

My goal was to reduce the amount I need to play to achieve certain goals due to time limitations. Any idea about how to multiply all the drops? Like instead of 1 cobblestone per stone, drop 2 or 3, same with ores, mobs, ...

**Comment by guplem** [comment]
@SmokeyStack Could you please clarify if there is now a way to modify the loot tables of vanilla blocks? 

The issue was closed, but I still need confirmation on whether this is possible or if there is any workaround to achieve the desired drop modifications. Specifically, I want to increase the drop rates for certain blocks and items (e.g., 2-3 cobblestones per stone). 

Thank you for your help.
