### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by ModMaker101** [Bedrock-OSS/bedrock-wiki#622]
Issue: The words on the front page when I click them, they don't redirect me.

Affected pages: I have to use the sidebar and can't use a quick home page.

Suggestions: I suggest that you make the homepage have what I said in my issue.

**Comment by SmokeyStack** [comment]
I could not reproduce this on my browser. Works fine on desktop and android, chrome

**Comment by SirLich** [comment]
@SmokeyStack I think hes' talking about how not all the home page titles are hyperlinks. We can likely just make them all hyperlinks and link to a token page:

![image](https://user-images.githubusercontent.com/18729296/231104884-3d4d260f-3665-4b49-84f2-0117eec86c63.png)

Also you could think about redoing the homepage links with a new/slightly different set of blocks, if you want to highlight different content.

**Comment by ModMaker101** [comment]
For the items icon could it maybe be a sword

**Comment by SmokeyStack** [comment]
> For the items icon could it maybe be a sword

We are discussing on new icons

**Comment by ModMaker101** [comment]
okey cool

**Comment by ModMaker101** [comment]
I see you fixed the hyperlinks

**Comment by ModMaker101** [comment]
Thanks

**Comment by ModMaker101** [comment]
Thanks for all you work.
