### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by ModMaker101** [Bedrock-OSS/bedrock-wiki#625]
Can you Use the Microsoft VSCode's syntax highlighting because I think VSCode does a pretty good job at doing syntax highlighting.
This is not an issue. If you don't want to do this can you do it, then in the systems button on the page.
![Screenshot 2023-04-12 074751](https://user-images.githubusercontent.com/119018978/231447865-b8181a05-d3d5-42eb-b0bd-9aceba323ed8.png)

**Comment by SmokeyStack** [comment]
We don't have any plans to switch to vscode's default syntax highlighting.
